### PR TITLE
Upgrade Symfony dependencies

### PR DESCRIPTION
**Pull request by zippex**
- allow the 5.x series of the Symfony components
- current tests are still green

### CODE REVIEW

**Comment by krichprollsch** [comment]
Hello @zippex, thank you for your PR :pray: 

Travis reports the tests failed with PHP 7.0 and 7.1 due to incompatibility with phpunit.

Could-you edit `.travis.yml` in your PR to remove these PHP versions ?
We can also remove hhvm which is useless now I think.

But we could add 7.3 and 7.4...
WDYT ?

**Comment by krichprollsch** [comment]
oh and of course we can drop PHP 5.6 too...

**Comment by zippex** [comment]
Finally... sorry for messing things up :)

**Comment by krichprollsch** [comment]
perfect :ok_hand: 
Thank you for the phpunit update :+1:

**Pull request merged**
